   INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Andrés','Guzmán','profesor@bolsadeideas.com','2017-12,11');
   INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Mr. John','Doe','john.doe@gmail.com','2017-11,11');
   INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Linus','Torvals','linus.torvalds@gmail.com','2017-11,12');
   INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Rasmus','Leordorf','ramus.leodorf@gmail.com', '2017-11,13');
   INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Erich','Gamma','erich.gamma@gmail.com','2017-11,14');
   INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Richard','Helm','richard.helm@gmail.com','2017-11,15');
   INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Ralph','Johnson','ralph.johnson@gmail.com','2017-11,16');
   INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Bombasto','Vlissides','bombasto.vlissides@gmail.com','2017-11,17');
   INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Dr. James','Gosling','james.gosling@gmail.com','2017-11,18');
   INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Magma','Lee','magma.lee@gmail.com','2017-12,19');
   INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Tornado', 'Roe', 'tornado.roe@gmail.com','2017-11,20');
   INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Jade', 'Doe', 'jane.doe@gmail.com','2018-03-06');